services:
    postgres:
        image: postgres:17-alpine
        volumes:
            - db_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=main
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - postgres

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:9
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
            PGADMIN_CONFIG_SERVER_MODE: "False"
        volumes:
            - pgadmin:/var/lib/pgadmin
        ports:
            - "80:80"
        networks:
            - postgres

    n8n:
        container_name: n8n
        image: n8nio/n8n
        volumes:
            - n8n_data:/competitions/node/.n8n
        ports:
            - "5678:5678"

networks:
    postgres:
        driver: bridge

volumes:
    minio-data:
    db_data:
    pgadmin:
    n8n_data:
